title:            My Tech Blog
description:      Technical articles on Java and open source technologies
#disqus_shortname: neohpstrtheme
reading_time:     false
words_per_minute: 200
logo:             images/elan-logo.gif
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
#url: http://elang2.github.io

menu:
  - title: 'Home'
    url: '/'
  - title: 'About the Author'
    url: '/about'
  - title: 'All Posts'
    url: '/posts'
#  - title: 'Tags'
#    url: '/tags'
#  - title: 'Categories'
#    url: '/categories'
#    type: 'categories'
#  - title: 'Favorites'
#    url: '#'
#    submenu:
#      - title: 'highlighter'
#        url: '/code-highlighting-post/'
#      - title: 'intro'
#        url: '/readability-post/'

# Owner/author information
owner:
  name:           Elankumaran Srinivasan
  site:           http://elang2.github.io/
  avatar:         images/avatar.jpg
  bio:            "I am a software engineer, Java and open source technonogy enthusiast."
  email:          elang2@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: Elang2Second
  facebook: elang.kumaran.7
  github: elang2
  stackexchange:
  linkedin: elankumaran-srinivasan-290851a4
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+', eg +AronBordin
  google_plus:    +elang2

social:
  - title: "github"
    url: "https://github.com/elang2"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/elankumaran-srinivasan-290851a4"
  - title: "youtube"
    url: "https://www.youtube.com/channel/UCfnSek-9HPWOx5e2pH7VFgg"
# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: pygments
markdown:    kramdown
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
